[package]
name = "grax"
authors = ["Kyle Braham <polymorphic92@gmail.com>"]
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.29"
ctrlc = "3.4"
nvml-wrapper = "0.11"
sysinfo = "0.35"

[profile.release]
lto = true
codegen-units = 1
